# Generated by Django 4.0.3 on 2022-03-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_screenshots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshots',
            name='file_name',
            field=models.ImageField(max_length=1000, upload_to='images/'),
        ),
    ]
